Merge branch '197143-nomethoderror-undefined-method-sort_by_attribute-for-nil-nilclass' into 'master'
Resolve "NoMethodError: undefined method `sort_by_attribute' for nil:NilClass"

Closes #197143

See merge request gitlab-org/gitlab!23161

(cherry picked from commit 0276f654051e218e91644174eeae2dd41250d8c7)

cf4ac1b3 Add sefeguard for empty union
3dc98245 Add fallback if union is returning nil and specs
65d87635 Add changelog entry
8000c1c8 Fix rubocop offence
0b653979 Add cr remarks